version: "3.3"
services:
        imanatask_core:
                container_name: imanatask_core
                build: ./imanatask-core
                ports:
                        - "8080:8080"
                depends_on:
                        - imanatask_db
                environment:
                        - MONGO_HOST=imanatask_db
                        - MONGO_PORT=27017
                        - MONGO_DB=imanatask
        imanatask_db:
                container_name: imanatask_db
                image: mongo
                ports:
                        - "27017:27017"
