version: "3.3"
services:
        web:
                container_name: web
                build: ./imanatask-web
                ports:
                        - "80:80"
                depends_on:
                        - core

        core:
                container_name: core
                build: ./imanatask-core
                ports:
                        - "8080:8080"
                depends_on:
                        - db
                environment:
                        - MONGO_HOST=db
                        - MONGO_PORT=27017
                        - MONGO_DB=imanatask
        db:
                container_name: db
                image: mongo
                ports:
                        - "27017:27017"
